apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: addrconvsvc-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - cashaddr.bitcoincash.org
    secretName: addrconvsvc-tls
  backend:
    serviceName: addrconvsvc
    servicePort: 86
  rules:
  - host: cashaddr.bitcoincash.org
    http:
      paths:
      - path: /
        backend:
          serviceName: addrconvsvc
          servicePort: 86
